### PR TITLE
build: deploy contracts to rinkeby

### LINKED ISSUE #3015: Deploy latest NitroAdjudicator to Rinkeby

### PR DESCRIPTION
**Pull request by kerzhner**
Fixes #3015

### CODE REVIEW

**Comment by geoknee** [comment]
We saw 
```
@statechannels/server-wallet: Segmentation fault (core dumped)
@statechannels/server-wallet: error Command failed with exit code 139.
@statechannels/server-wallet: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@statechannels/server-wallet: error Command failed with exit code 139.
@statechannels/server-wallet: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
several times trying to run tests on this branch. It seems unlikely to me that this was caused by the changeset. It may have been a transient problem on circle, since it passed when I reran it this morning .

**Review by geoknee — APPROVED** [review]

**Comment by geoknee** [comment]
😞 the seg fault reappeared when the tests run on master post merge.

**Comment by geoknee** [comment]
@kerzhner there is an `.env.rinkeby` file -- should this have been updated? https://github.com/statechannels/statechannels/pull/3018

**Comment by andrewgordstewart** [comment]
Do the test-stats file reveal anything useful?

**Comment by geoknee** [comment]
Not that I can discern...

**Comment by kerzhner** [comment]
> @kerzhner there is an `.env.rinkeby` file -- should this have been updated? #3018

@geoknee I have used that file to run tests against Rinkeby. I think it's easy to forget to update that file. We also run tests against Rinkeby pretty rarely.

**Pull request merged**
