### PR TITLE
circleCI: Separate with-peers tests from other server-wallet tests

### PR DESCRIPTION
**Pull request by NiloCK**
## Problem

From #3337: A run of CircleCI takes 7+ minutes, adding substantial friction to commit + merge process. Regrouped with-peers test can run in parallel with other tests from server-wallet, cutting total run time by 1-2 minutes.

## Changes

1. config.yml updated with a call of `yarn test:with-peers`
2. with-peers tests regrouped in top-level directory, to exclude them from base config used by `yarn test`
3. jest.with-peers.config.js updated to reflect new location of tests

## How Has This Been Tested? [Optional] 

- tests run locally with expected results
- observed completion of circleCI run

---
### Code quality
- [x] I have written clear commit messages
- [x] I have performed a self-review of my own code
- [x] This change does not have an unduly wide scope
- [x] I have separated logic changes from refactor changes (formatting, renames, etc.)
- [x] I have commented my code wherever necessary (can be 0)
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
### Project management
- [x] I have applied the [appropriate labels](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#b304e56734a74dfbb341b8b4b27b1c0c)
- [x] I have linked to all relevant issues (can be 0)
- [x] I have added all dependent tickets (can be 0)
- [x] I have assigned myself to this PR
- [x] I have chosen the appropriate [pipeline](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#d534e68e7edc46fe8a4cda61b2258c4e) on zenhub for the linked issue

### CODE REVIEW

**Review by geoknee — APPROVED** [review]
Looks good to me!

@NiloCK are there any other optimisations that occur to you, having dug into our CI pipeline? 

Also I'm curious if you made use of any "update imports" feature of your editor when making changes that moved `.ts` files, or if you ended up doing that manually.

**Comment by geoknee** [comment]
I just noticed there are a lot errors logged out during the newly split-off test:

https://app.circleci.com/pipelines/github/statechannels/statechannels/12078/workflows/d5b5ece5-be47-44a5-ae25-8930f5141cd8/jobs/58895

is that expected?

**Comment by NiloCK** [comment]
I think that those errors are NOT expected, and I'll have a closer look shortly to see if they're a problem. Interesting that the tests passed.

**Comment by geoknee** [comment]
Could be related to this https://github.com/facebook/jest/issues/8688

**Comment by wunnaii** [comment]
Hey Colin, please link PRs to related issue if it exists :) 
I'm in the middle of updating the PR template to include a URL to these intructions : https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues

Unfortunately, i believe you have to link in zenhub for now :(

**Comment by NiloCK** [comment]
> I just noticed there are a lot errors logged out during the newly split-off test:

After some head scratching: these errors are being thrown because
 - setup for the `server_wallet_test` db is a separate circleCI [`run`](https://github.com/statechannels/statechannels/blob/57f8d2824518e2aef5aa9109bce460034e5ea315/.circleci/config.yml#L140-L145) step inside the `test` process. IE, not run in the with-peers test process.
 - truncation of the `server_wallet_test` db is a consequence of the [setup of knex instances](https://github.com/statechannels/statechannels/blob/57f8d2824518e2aef5aa9109bce460034e5ea315/packages/server-wallet/jest/knex-setup-teardown.ts#L32-L35) perscribed by the base jest config used by `yarn test`, `yarn test:with-peers`, etc. Part of the setup is to truncate prior contents, but that db doesn't have prior contents (or exist).

The errors are smelly but harmless.

> I'm curious if you made use of any "update imports" feature of your editor when making changes that moved .ts files

VSCode updated them successfully but did not also automatically apply prettification, which required the "open a problem file, inserte white-space, save" fix.

> are there any other optimisations that occur to you, having dug into our CI pipeline?

The biggest bottleneck remains the long run of server-wallet tests. Possibly there could be a systematic splitting and parallelization of these tests. I don't know much about the `resource_class` flag for CircleCI config - maybe worth toying with for the `test` job.

**Pull request merged**
