### PR TITLE
add *transferAllAssets tests

### PR DESCRIPTION
**Pull request by geoknee**
These replace `concludePushOutcomeAndTransferAll.test.ts` and `pushOutcomeAndTransferAll.test.ts`.

⚠️ base not master. Towards #3624

### CODE REVIEW

**Comment by geoknee** [comment]
I'm going to try and rewrite history here to make the diff easier to read.

**Comment by geoknee** [comment]
Partial success. Note to reviewer: just look at fb34ba69934fd559a20c1c8c0e079a0c5d02cfe9 (the only thing missing is the filename change).

**Comment by NiloCK** [comment]
> Partial success. Note to reviewer: just look at [fb34ba6](https://github.com/statechannels/statechannels/commit/fb34ba69934fd559a20c1c8c0e079a0c5d02cfe9) (the only thing missing is the filename change).

That's great! Thanks.

**Review by NiloCK — APPROVED** [review]
I read this, and made sense of it as I went, but there's a fair amount of detailed implementation in here (parsing data from loosely typed objects, etc). I think it's good to merge this in but keep in mind that we may have to circle back when getting the target branch running successfully against Circle.

**Comment by geoknee** [comment]
> I read this, and made sense of it as I went, but there's a fair amount of detailed implementation in here (parsing data from loosely typed objects, etc). I think it's good to merge this in but keep in mind that we may have to circle back when getting the target branch running successfully against Circle.

Yeah we will need to get a ✅  on #3624 before merging that in to master. These tests pass for me locally, so I am hoping when it all comes together it just works or only requires some small tweaks.

**Pull request merged**
