### PR TITLE
Include jest typescript folders in linting

### PR DESCRIPTION
**Pull request by lalexgap**
The `jest` folder is currently excluded from linting which makes editing these files more annoying.

This change simple includes the jest folder typescript files in linting.

### CODE REVIEW

**Comment by NiloCK** [comment]
Jumping in quickly to :+1: . This accounts for at least 1/3 of my recent headaches.

I am happy to review this in half an hour or so.

**Review by NiloCK — APPROVED** [review]
Sorry I didn't get to this yesterday! Looks good.

@andrewgordstewart You authored the deleted `.eslintignore` line, but it looks like it was only 'written' in the sense of having been an existing config file that was copied. Any objection to this PR?

**Comment by andrewgordstewart** [comment]
As much as I like bikes, I don't care what colour their storage structure is.

I enthusiastically approve this PR.

**Review by andrewgordstewart — APPROVED** [review]
As much as I like bikes, I don't care what colour their storage structure is.

I enthusiastically approve this PR.

**Pull request merged**
